### ISSUE TITLE
CentOS 6.6 and centos 6.5 cdr-stat start error (for Asterisk)

### ISSUE THREAD

**Issue by alexjd2008** [Star2Billing/cdr-stats#36]
after install il see this error in log /var/log/cdr-stats/err-apache-cdr-stats.log

[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7] mod_wsgi (pid=3942): Target WSGI script '/usr/share/cdr_stats/django.wsgi' cannot be loaded as Python module.
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7] mod_wsgi (pid=3942): SystemExit exception raised by WSGI script '/usr/share/cdr_stats/django.wsgi' ignored.
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7] Traceback (most recent call last):
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7]   File "/usr/share/cdr_stats/django.wsgi", line 31, in <module>
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7]     import settings
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7]   File "/usr/share/cdr_stats/settings.py", line 533, in <module>
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7]     sys.exit(1)
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7] SystemExit: 1

what is it ?

**Comment by areski** [comment]
From the output of the install script, it seems you have connectivity issues with github from your server. 
"""
Initialized empty Git repository in /usr/src/cdr-stats/.git/
github.com[0: 192.30.252.128]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
"""
I would recommend to try to investigate this.
